import {
	IconGithub,
	IconSupabase,
	IconVercel,
	IconStripe,
	IconNotion,
	IconGoogle,
	IconCloudflare,
	IconFigma,
	IconSlack,
	IconLinear,
	IconAWS,
} from "../Icons";
import type { IntegrationDef } from "./types";

// Preact JSX factory is needed for the icon arrow functions
import { h } from "preact";

export const INTEGRATIONS: IntegrationDef[] = [
	{
		id: "github",
		name: "GitHub",
		description: "Repos, PRs, issues, and code search",
		icon: () => h(IconGithub, { size: 22 }),
		available: true,
		mcpServerName: "github",
	},
	{
		id: "supabase",
		name: "Supabase",
		description: "Database, auth, storage, and edge functions",
		icon: () => h(IconSupabase, { size: 22 }),
		available: true,
		tokenBased: true,
		tokenEnvKey: "SUPABASE_ACCESS_TOKEN",
		tokenUrl: "https://supabase.com/dashboard/account/tokens",
		tokenHint: "Generate a token at supabase.com → Account → Access Tokens",
		mcpServerName: "supabase",
		mcpCommand: "npx",
		mcpArgs: ["-y", "@supabase/mcp-server-supabase"],
	},
	{
		id: "vercel",
		name: "Vercel",
		description: "Deployments, projects, and domains",
		icon: () => h(IconVercel, { size: 22 }),
		available: true,
		tokenBased: true,
		tokenEnvKey: "VERCEL_TOKEN",
		tokenUrl: "https://vercel.com/account/tokens",
		tokenHint: "Generate a token at vercel.com → Account → Tokens",
		mcpServerName: "vercel",
		mcpCommand: "npx",
		mcpArgs: ["-y", "vercel-mcp@latest"],
	},
	{
		id: "stripe",
		name: "Stripe",
		description: "Payments, subscriptions, and invoices",
		icon: () => h(IconStripe, { size: 22 }),
		available: true,
		tokenBased: true,
		tokenEnvKey: "STRIPE_SECRET_KEY",
		tokenUrl: "https://dashboard.stripe.com/apikeys",
		tokenHint: "Copy your Secret Key from the Stripe Dashboard → API Keys",
		mcpServerName: "stripe",
		mcpCommand: "npx",
		mcpArgs: ["-y", "@stripe/mcp"],
	},
	{
		id: "notion",
		name: "Notion",
		description: "Pages, databases, and workspaces",
		icon: () => h(IconNotion, { size: 22 }),
		available: true,
		tokenBased: true,
		tokenEnvKey: "NOTION_API_KEY",
		tokenUrl: "https://www.notion.so/my-integrations",
		tokenHint:
			"Create an integration at notion.so/my-integrations and copy the secret",
		mcpServerName: "notion",
		mcpCommand: "npx",
		mcpArgs: ["-y", "@notionhq/notion-mcp-server"],
	},
	{
		id: "google",
		name: "Google (Gmail, Drive, Sheets)",
		description: "Email, documents, spreadsheets, and calendar",
		icon: () => h(IconGoogle, { size: 22 }),
		available: true,
		tokenBased: true,
		tokenEnvKey: "GOOGLE_API_KEY",
		tokenUrl: "https://console.cloud.google.com/apis/credentials",
		tokenHint:
			"Create an API key or Service Account at Google Cloud Console → APIs & Services → Credentials",
		mcpServerName: "google",
		mcpCommand: "npx",
		mcpArgs: ["-y", "@anthropic-ai/mcp-server-google-maps"],
	},
	{
		id: "cloudflare",
		name: "Cloudflare",
		description: "DNS, Workers, Pages, and CDN",
		icon: () => h(IconCloudflare, { size: 22 }),
		available: true,
		tokenBased: true,
		tokenEnvKey: "CLOUDFLARE_API_TOKEN",
		tokenUrl: "https://dash.cloudflare.com/profile/api-tokens",
		tokenHint:
			"Create an API token at Cloudflare Dashboard → Profile → API Tokens",
		mcpServerName: "cloudflare",
		mcpCommand: "npx",
		mcpArgs: ["-y", "@cloudflare/mcp-server-cloudflare"],
	},
	{
		id: "figma",
		name: "Figma",
		description: "Design files, components, and styles",
		icon: () => h(IconFigma, { size: 22 }),
		available: true,
		tokenBased: true,
		tokenEnvKey: "FIGMA_ACCESS_TOKEN",
		tokenUrl: "https://www.figma.com/developers/api#access-tokens",
		tokenHint:
			"Generate a personal access token at Figma → Settings → Personal Access Tokens",
		mcpServerName: "figma",
		mcpCommand: "npx",
		mcpArgs: ["-y", "figma-developer-mcp"],
	},
	{
		id: "slack",
		name: "Slack",
		description: "Messages, channels, and team communication",
		icon: () => h(IconSlack, { size: 22 }),
		available: true,
		tokenBased: true,
		tokenEnvKey: "SLACK_BOT_TOKEN",
		tokenUrl: "https://api.slack.com/apps",
		tokenHint:
			"Create a Slack app → OAuth & Permissions → Bot User OAuth Token (xoxb-...)",
		mcpServerName: "slack",
		mcpCommand: "npx",
		mcpArgs: ["-y", "@modelcontextprotocol/server-slack"],
	},
	{
		id: "linear",
		name: "Linear",
		description: "Issues, projects, and team workflows",
		icon: () => h(IconLinear, { size: 22 }),
		available: true,
		tokenBased: true,
		tokenEnvKey: "LINEAR_API_KEY",
		tokenUrl: "https://linear.app/settings/account/api",
		tokenHint:
			"Generate a personal API key at Linear → Settings → Account → API",
		mcpServerName: "linear",
		mcpCommand: "npx",
		mcpArgs: ["-y", "mcp-linear"],
	},
	{
		id: "aws",
		name: "AWS",
		description: "S3, Lambda, DynamoDB, and cloud services",
		icon: () => h(IconAWS, { size: 22 }),
		available: true,
		tokenBased: true,
		tokenEnvKey: "AWS_ACCESS_KEY_ID",
		tokenUrl: "https://console.aws.amazon.com/iam/home#/security_credentials",
		tokenHint:
			"Create an access key at IAM → Security Credentials → Access Keys. Also set AWS_SECRET_ACCESS_KEY and AWS_REGION in Environment tab.",
		mcpServerName: "aws",
		mcpCommand: "npx",
		mcpArgs: ["-y", "aws-mcp"],
	},
];
