#!/usr/bin/env bash
set -euo pipefail

# Codeck Development Setup — Hosted Mode
#
# Installs everything from scratch on a fresh VPS and runs Codeck
# in hosted mode: daemon on host (systemd) + runtime in Docker.
#
# Usage (from any directory):
#   curl -fsSL https://raw.githubusercontent.com/cyphercr0w/codeck/main/scripts/dev-setup.sh | sudo bash
#
# Or if you already have the repo:
#   sudo bash scripts/dev-setup.sh
#
# After code changes:
#   npm run build && docker build -t codeck -f docker/Dockerfile . && sudo systemctl restart codeck

NODE_MAJOR=22
CODECK_USER="codeck"
CODECK_REPO="https://github.com/cyphercr0w/codeck.git"
CODECK_INSTALL_DIR="/opt/codeck"

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
NC='\033[0m'

log()  { echo -e "${GREEN}[+]${NC} $*"; }
warn() { echo -e "${YELLOW}[!]${NC} $*"; }
error(){ echo -e "${RED}[✗]${NC} $*" >&2; exit 1; }
step() { echo -e "\n${CYAN}── $* ──${NC}"; }

# Determine repo dir: use the script's own location if available,
# otherwise fall back to the install dir (pipe-from-curl case).
if [[ -n "${BASH_SOURCE[0]:-}" && "${BASH_SOURCE[0]}" != "bash" ]]; then
  CODECK_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
else
  CODECK_DIR="$CODECK_INSTALL_DIR"
fi

# ─── Pre-flight ──────────────────────────────────────────────────────

step "Pre-flight"

[[ "$(uname -s)" == "Linux" ]] || error "Linux required"
[[ "$EUID" -eq 0 ]] || error "Run as root: sudo bash scripts/dev-setup.sh"
command -v systemctl &>/dev/null || error "systemd required"

# ─── System deps ─────────────────────────────────────────────────────

step "System dependencies"

apt-get update -qq
apt-get install -y -qq curl git >/dev/null
log "Done"

# ─── Clone repo (if not already present) ─────────────────────────────

step "Codeck repo"

if [[ -f "$CODECK_DIR/package.json" ]]; then
  log "Repo already at $CODECK_DIR"
else
  log "Cloning into $CODECK_DIR ..."
  git clone "$CODECK_REPO" "$CODECK_DIR"
  log "Cloned"
fi

# ─── Node.js ─────────────────────────────────────────────────────────

step "Node.js $NODE_MAJOR"

if command -v node &>/dev/null; then
  ver=$(node -v | sed 's/v//' | cut -d. -f1)
  if [[ "$ver" -ge "$NODE_MAJOR" ]]; then
    log "Node.js $(node -v) OK"
  else
    curl -fsSL "https://deb.nodesource.com/setup_${NODE_MAJOR}.x" | bash - >/dev/null 2>&1
    apt-get install -y -qq nodejs >/dev/null
    log "Node.js $(node -v) installed"
  fi
else
  curl -fsSL "https://deb.nodesource.com/setup_${NODE_MAJOR}.x" | bash - >/dev/null 2>&1
  apt-get install -y -qq nodejs >/dev/null
  log "Node.js $(node -v) installed"
fi

# ─── Docker ──────────────────────────────────────────────────────────

step "Docker"

if command -v docker &>/dev/null; then
  log "Docker already installed"
else
  curl -fsSL https://get.docker.com | sh >/dev/null 2>&1
  systemctl enable docker >/dev/null
  systemctl start docker
  log "Docker installed"
fi

# ─── User ────────────────────────────────────────────────────────────

step "User: $CODECK_USER"

if ! id "$CODECK_USER" &>/dev/null; then
  useradd -r -m -s /bin/bash "$CODECK_USER"
  log "Created"
fi

usermod -aG docker "$CODECK_USER" 2>/dev/null || true

CODECK_HOME="/home/$CODECK_USER"
for dir in "$CODECK_HOME/workspace" "$CODECK_HOME/.codeck" "$CODECK_HOME/.claude" "$CODECK_HOME/.ssh" "$CODECK_HOME/.config/gh"; do
  mkdir -p "$dir"
done
chmod 700 "$CODECK_HOME/.codeck" "$CODECK_HOME/.claude" "$CODECK_HOME/.ssh"
chown -R "$CODECK_USER:$CODECK_USER" "$CODECK_HOME"

# Sudoers for self-deploy (restart service + Docker compose)
cat > /etc/sudoers.d/codeck <<'SUDOERS'
codeck ALL=(ALL) NOPASSWD: /usr/bin/systemctl restart codeck
codeck ALL=(ALL) NOPASSWD: /usr/bin/systemctl stop codeck
codeck ALL=(ALL) NOPASSWD: /usr/bin/systemctl start codeck
codeck ALL=(ALL) NOPASSWD: /usr/bin/docker compose *
codeck ALL=(ALL) NOPASSWD: /usr/bin/chown *
SUDOERS
chmod 440 /etc/sudoers.d/codeck
log "User ready, sudoers configured"

# ─── Build ───────────────────────────────────────────────────────────

step "Install & build"

cd "$CODECK_DIR"
chown -R "$CODECK_USER:$CODECK_USER" "$CODECK_DIR"

sudo -u "$CODECK_USER" npm ci --ignore-scripts 2>&1 | tail -3
sudo -u "$CODECK_USER" npm run build 2>&1 | tail -5
log "Built"

# ─── Docker images ───────────────────────────────────────────────────

step "Docker images"

docker build -t codeck-base -f docker/Dockerfile.base . 2>&1 | tail -5
docker build -t codeck -f docker/Dockerfile . 2>&1 | tail -5
log "Docker images ready"

# ─── Environment file ────────────────────────────────────────────────

step "Environment file"

CODECK_UID=$(id -u "$CODECK_USER")
CODECK_GID=$(id -g "$CODECK_USER")

ENV_FILE="$CODECK_DIR/.env"
cat > "$ENV_FILE" <<EOF
# Codeck hosted mode — generated by dev-setup.sh
CODECK_UID=$CODECK_UID
CODECK_GID=$CODECK_GID
EOF
chown "$CODECK_USER:$CODECK_USER" "$ENV_FILE"
log "Created $ENV_FILE"

# ─── Systemd ─────────────────────────────────────────────────────────

step "Systemd service"

cat > /etc/systemd/system/codeck.service <<'UNIT'
[Unit]
Description=Codeck - Claude Code Sandbox
After=network.target docker.service
Requires=docker.service

[Service]
Type=simple
User=codeck
Group=codeck
WorkingDirectory=/opt/codeck

Environment="PATH=/usr/local/bin:/usr/bin:/bin"
Environment="NODE_ENV=production"
Environment="CODECK_DAEMON_PORT=80"
Environment="CODECK_RUNTIME_URL=http://127.0.0.1:7777"
Environment="CODECK_RUNTIME_WS_URL=http://127.0.0.1:7778"
Environment="CODECK_DIR=/workspace/.codeck"
Environment="CODECK_PROJECT_DIR=/opt/codeck"
Environment="CODECK_COMPOSE_FILE=docker/compose.managed.yml"
Environment="HOME=/home/codeck"

ExecStartPre=/usr/bin/docker compose -f /opt/codeck/docker/compose.managed.yml up -d --wait
ExecStart=/usr/bin/node /opt/codeck/apps/daemon/dist/index.js
ExecStopPost=/usr/bin/docker compose -f /opt/codeck/docker/compose.managed.yml down

Restart=always
RestartSec=10
CPUQuota=100%
MemoryMax=512M
NoNewPrivileges=true
ProtectSystem=full
AmbientCapabilities=CAP_NET_BIND_SERVICE

[Install]
WantedBy=multi-user.target
UNIT

systemctl daemon-reload
systemctl enable codeck >/dev/null 2>&1
systemctl start codeck
log "Service started"

sleep 3
systemctl is-active --quiet codeck && log "Running!" || warn "Check: journalctl -u codeck -n 30"

# ─── Symlinks ────────────────────────────────────────────────────────

step "Symlinks"

# /workspace → actual workspace dir so agent memory paths resolve correctly
if [[ ! -e /workspace ]]; then
  ln -sf "$CODECK_HOME/workspace" /workspace
  log "/workspace → $CODECK_HOME/workspace"
elif [[ -L /workspace ]]; then
  log "/workspace symlink already exists ($(readlink /workspace))"
else
  warn "/workspace exists as a real directory — skipping (may be Docker volume)"
fi

# repo → workspace/codeck so users can develop Codeck from inside the sandbox
WORKSPACE_LINK="$CODECK_HOME/workspace/codeck"
if [[ ! -e "$WORKSPACE_LINK" ]]; then
  ln -s "$CODECK_DIR" "$WORKSPACE_LINK"
  chown -h "$CODECK_USER:$CODECK_USER" "$WORKSPACE_LINK"
  log "$CODECK_DIR → $WORKSPACE_LINK"
else
  log "Workspace codeck link already exists"
fi

# ─── Git identity ────────────────────────────────────────────────────

step "Git identity"

sudo -u "$CODECK_USER" git config --global user.name "Codeck"
sudo -u "$CODECK_USER" git config --global user.email "261683274+cyphercr0w@users.noreply.github.com"
log "git user.name=Codeck"

# ─── Firewall ────────────────────────────────────────────────────────

if command -v ufw &>/dev/null; then
  ufw allow 80/tcp >/dev/null 2>&1 || true
fi

# ─── Done ─────────────────────────────────────────────────────────────

PUBLIC_IP=$(curl -fsSL --max-time 5 https://ifconfig.me 2>/dev/null || hostname -I | awk '{print $1}')

echo ""
echo -e "${GREEN}════════════════════════════════════════${NC}"
echo -e "${GREEN}  Codeck dev setup complete!${NC}"
echo -e "${GREEN}════════════════════════════════════════${NC}"
echo ""
echo -e "  Open: ${CYAN}http://${PUBLIC_IP}${NC}"
echo ""
echo "  After code changes:"
echo "    cd $CODECK_DIR"
echo "    npm run build && docker build -t codeck -f docker/Dockerfile ."
echo "    sudo systemctl restart codeck"
echo ""
echo "  Logs:"
echo "    journalctl -u codeck -f        — daemon"
echo "    docker logs codeck-runtime -f  — runtime"
echo ""
